environments:
  dev:
    values:
      - values/dev-values.yaml
      - values/secrets.enc.yaml
      - values/velero-values.yaml
      - values/kube-prometheus-values.yaml
---
releases:
  - name: server
    namespace: fullstack
    chart: .
    values:
      - values/dev-values.yaml
      - values/secrets.enc.yaml

  - name: velero
    namespace: velero
    createNamespace: true
    chart: vmware-tanzu/velero
    version: 5.0.2
    values:
      - values/velero-values.yaml

  - name: kube-prometheus-stack
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    version: 58.5.0
    values:
      - values/kube-prometheus-values.yaml

  - name: kubectl-cost
    namespace: monitoring
    createNamespace: false
    chart: prometheus-community/kubectl-cost
    version: 0.1.2
    values:
      - replicas: 1
