apiVersion: v1
kind: Config
clusters:
- name: eks
  cluster:
    server: https://C532DE33C6295CDDFC2609015347AA22.gr7.us-east-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...  # long cert line you already pasted
contexts:
- name: eks
  context:
    cluster: eks
    user: eks-user
current-context: eks
users:
- name: eks-user
  user:
    token: k8s-aws-v1.aHR0cHM6Ly9zdHMudXMtZWFzdC0yLmFtYXpvbmF3cy5jb20vP0FjdGlvbj1...  # full token from `aws eks get-token`
