image:
  repository:
    server: gantagouthamyadav/fullstack-server
    client: gantagouthamyadav/fullstack-client
  tag: latest

replicaCount: 1

env:
  - name: MONGO_URI
    value: {{ .Values.env.MONGO_URI | quote }}

mongodb:
  architecture: standalone
  useStatefulSet: false
  auth:
    enabled: false
  primary:
    persistence:
      enabled: true
      storageClass: gp2
      size: 8Gi
