grafana:
  adminPassword: prom-operator
  service:
    type: LoadBalancer

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /var/lib/grafana/dashboards/custom

  dashboards:
    default:
      kubecost-dashboard:
        file: /var/lib/grafana/dashboards/custom/kubecost-dashboard.json

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    alertingEndpoints:
      - name: default
        namespace: monitoring

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'slack-notifications'
    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - send_resolved: true
            channel: '#alerts'
            username: 'prometheus'
            api_url: '<REPLACE_WITH_YOUR_SLACK_WEBHOOK_URL>'

