global:
  grafana:
    enabled: false

  prometheus:
    fqdn: http://kube-prometheus-stack-prometheus.monitoring.svc

kubecostModel:
  enabled: true

networkCosts:
  enabled: true

serviceMonitor:
  enabled: true

