globalConfig:
  signing_key: ""

prometheus:
  enabled: false  # Already using kube-prometheus-stack

grafanaDashboards:
  create: false   # 🔴 Disable Robusta’s dashboard injection (prevents ${datasource} errors)

grafanaRenderer:
  enabled: false  # 🔴 Disable Robusta's PDF/renderer service (not needed)

sinksConfig:
  - sink_type: "slack"
    name: "main-slack"
    slack_channel: "#alerts"
    slack_webhook: "https://hooks.slack.com/services/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"

runner:
  sendAdditionalTelemetry: false
  extraEnvVars:
    - name: ROBUSTA_DISABLE_TELEMETRY
      value: "true"


