{
 "title": "NG Endurance",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "\n# NG ENDURANCE\n### POWERED BY BLUE BOX\n\n\n\n\n\n"
   }
  },
  {
   "title": "ekW MAIN ENGINE 1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG1\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=380 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;"
    }
   ]
  },
  {
   "title": "ekW MAIN ENGINE 2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG2\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=381 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;"
    }
   ]
  },
  {
   "title": "ekW MAIN ENGINE 3",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG3\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=382 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;"
    }
   ]
  },
  {
   "title": "ekW MAIN ENGINE 4",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG4\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=383 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;"
    }
   ]
  },
  {
   "title": "Speed - power curve",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"KW Main Propulsion Port\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=397 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"KW Main Propulsion Starboard\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=401 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Speed\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=425 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Depth AFT\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=368 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Depth FWD\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=369 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "Power Production Gen Sets (ekW)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG1\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=380 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG2\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=381 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG3\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=382 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG4\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=383 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "Hotel load (ekW)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG1\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=380 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG2\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=381 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG3\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=382 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG4\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=383 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Power Prop 2\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=401 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Power Prop 1\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=397 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Thruster 1\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=406 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Thruster 2\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=408 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "SFoC & Load - Engine 1 ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "string", "label": "SFoC (g/kWh)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG1\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=380 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"FoC DG1\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=372 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "SFoC & Load - Engine 4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 43 },
   "yaxes": [
    { "format": "string", "label": "SFoC (g/kWh)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG4\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=383 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"FoC DG4\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=375 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "SFoC & Load - Engine 2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "string", "label": "SFoC (g/kWh)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG2\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=381 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"FoC DG2\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=373 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "SFoC & Load - Engine 3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 52 },
   "yaxes": [
    { "format": "string", "label": "SFoC (g/kWh)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG3\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=382 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"FoC DG3\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=374 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "SFoC curve - Engine 1 ",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG1\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=380 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"FoC DG1\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=372 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "SFoC curve - Engine 4",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG4\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=383 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"FoC DG4\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=375 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "SFoC curve - Engine 2",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG2\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=381 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"FoC DG2\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=373 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "SFoC curve - Engine 3",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 69 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Active Power DG3\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=382 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"FoC DG3\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=374 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "Instant Fuel Consumption (l/h)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Net Fuel Flow DG1\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=372 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Net Fuel Flow DG2\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=373 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Net Fuel Flow DG3\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=374 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Net Fuel Flow DG4\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=375 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "Main Propulsion Power (kW)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"KW Main Propulsion Port\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=397 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"KW Main Propulsion Starboard\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=401 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "Speed over surface (knots)",
   "type": "graph",
   "gridPos": { "h": 19, "w": 23, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "velocityknot" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Speed over water\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=425 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "Heel angle (deg)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Heel\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=396 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "Draft & trim",
   "type": "graph",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Draft Fwd\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=367 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"Draft Aft\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=370 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  },
  {
   "title": "Main Propulsion RPM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"RPM Main Propulsion 1\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=398 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    },
    {
     "rawSql": "SELECT\n  $__time(timestamp/1000),\n  engineeringvalue as \"RPM Main Propulsion 2\"\nFROM\n  analogsignalfilteredlast\nWHERE\n id=402 and\n timestamp >= $__unixEpochFrom()::bigint*1000 and\n timestamp <= $__unixEpochTo()::bigint*1000\norder by timestamp;\n"
    }
   ]
  }
 ]
}