initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.8.2
    volumeMounts:
      - mountPath: /target
        name: plugins

volumeMounts:
  - mountPath: /plugins
    name: plugins

volumes:
  - name: plugins
    emptyDir: {}

credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id = {{ .Env.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key = {{ .Env.AWS_SECRET_ACCESS_KEY }}

configuration:
  backupStorageLocations:
    - name: default
      provider: aws
      bucket: "{{ .Env.VELERO_BUCKET }}"
      config:
        region: us-east-2

  volumeSnapshotLocations:
    - name: default
      provider: aws
      config:
        region: us-east-2
