apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client
  labels:
    app: {{ .Release.Name }}-client
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-client
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-client
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image }}:{{ .Values.client.tag }}"
          imagePullPolicy: {{ .Values.client.pullPolicy }}
          ports:
            - containerPort: {{ .Values.client.port }}
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"


