apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubectl-cost
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubectl-cost
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - monitoring
