name: Full DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  TFSTATE_BUCKET: ${{ secrets.TFSTATE_BUCKET }}
  CHART_BUCKET: ${{ secrets.CHART_BUCKET }}

jobs:
  quality-gates:
    name: Lint, Test, SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd server && npm ci
          cd ../client && npm ci
          cd ..

      - name: Lint & Test
        run: |
          cd server && npm run lint && npm test || true
          cd ../client && npm run lint && npm test || true
          cd ..

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v1
        with:
          args: >
            -Dsonar.projectKey=gouthamyadavganta_fullstack-devsecops-project
            -Dsonar.organization=gouthamyadavganta
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push:
    name: Build & Push Docker Images
    needs: quality-gates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build & Push Server Image
        uses: docker/build-push-action@v4
        with:
          context: server
          push: true
          tags: gantagouthamyadav/fullstack-server:${{ github.sha }}

      - name: Build & Push Client Image
        uses: docker/build-push-action@v4
        with:
          context: client
          push: true
          tags: gantagouthamyadav/fullstack-client:${{ github.sha }}

  terraform:
    name: Terraform Infra Provisioning
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init & Apply
        working-directory: terraform-aws-infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init -backend-config="bucket=${{ env.TFSTATE_BUCKET }}"
          terraform apply -auto-approve

  helm-release:
    name: Helm Package & S3 Push
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Package & Push Helm Chart
        run: |
          cd fullstack-app
          helm package . --version 0.1.${{ github.run_number }} --app-version ${{ github.sha }}
          aws s3 cp fullstack-app-0.1.${{ github.run_number }}.tgz s3://${{ env.CHART_BUCKET }}/

  argocd-sync:
    name: Argo CD Sync
    needs: helm-release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Argo CD Sync
        uses: argoproj/argocd-action@v2
        with:
          argocd_server: ${{ secrets.ARGOCD_SERVER }}
          argocd_token: ${{ secrets.ARGOCD_TOKEN }}
          args: app sync fullstack-app

  healthcheck:
    name: Verify Deployment
    needs: argocd-sync
    runs-on: ubuntu-latest
    steps:
      - name: Curl health endpoint
        run: |
          curl --fail http://fullstack.3.132.115.98.nip.io/api/posts || exit 1
