apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubecost.github.io/cost-analyzer/
    chart: cost-analyzer
    targetRevision: 1.107.1  # or latest
    helm:
      values: |
        global:
          prometheus:
            enabled: false  # Use your Prometheus from infra
          grafana:
            enabled: false  # Use your Grafana from infra
        kubecostToken: your-kubecost-token-here
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

