apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robusta
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gouthamyadavganta/fullstack-mern-app.git
    targetRevision: HEAD
    path: infra/robusta
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: robusta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
