apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robusta
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://robusta-charts.storage.googleapis.com
    chart: robusta
    targetRevision: 0.10.1
    helm:
      values: |
        clusterName: devops-eks-cluster
        enablePrometheusStack: false
  destination:
    server: https://kubernetes.default.svc
    namespace: robusta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

