apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 6.0.0
    helm:
      values: |
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.8.2
            volumeMounts:
              - mountPath: /target
                name: plugins
        configuration:
          provider: aws
          backupStorageLocation:
            - name: default
              bucket: fullstack-mern-velero-backups
              provider: aws
              config:
                region: us-east-2
          volumeSnapshotLocation:
            - name: default
              provider: aws
              config:
                region: us-east-2
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

